### PR TITLE
Error fixed

### PR DESCRIPTION
**Pull request by yathomasi**
link issue fixed
all entries are given by getUserEntryIds
exception handling to the individual instead of as a whole

### CODE REVIEW

**Comment by spinach** [comment]
Hello,

Just to be clear, does this fix the issues? does it work with those changes?

Thanks a lot for submitting a PR for this!

**Comment by yathomasi** [comment]
@spinach yes it fixes the current issues the other guy got.
But there is still one problem left: I also made a new issue for this problem,
try opening a league in incognito or logged out:
`https://fantasy.premierleague.com/api/leagues-classic/51/standings/?page_new_entries=1&page_standings=1&phase=1`
Sometimes you cannot access them because it asks for authentication.
Fixing this will fix all
See this issue once: [Athorization Error](https://github.com/spinach/FantasyPremierLeague.py/issues/13)

**Comment by yathomasi** [comment]
@spinach  these new commits resolve #11  and other issues not mentioned.
So it works completely with new changes made by FPL.

**Comment by yathomasi** [comment]
You have a TODO list to implement it on a website.
I have the code in  [fantasyplayers](https://github.com/yathomasi/fantasyplayersl).
And also hosted in heroku in [https://fantasyplayers.herokuapp.com](https://fantasyplayers.herokuapp.com/)
The UI is not good for now and that can be improved.

**Comment by spinach** [comment]
woah awesome work mate, I checked the website and it works pretty well, awesome job!

**Comment by yathomasi** [comment]
@spinach  Thanks !!!

**Pull request merged**
